import { ManagerLanguageMode } from '../config/settings';

export type ManagerLocale = 'en' | 'ja';

const MANAGER_TEXT = {
  en: {
    htmlLang: 'en',
    pageTitle: 'GHCC Custom Provider',
    sidebar: {
      eyebrow: 'Settings',
      description: 'Add chat endpoints and choose which ones Copilot Chat should expose at the same time.',
      storedSettings: 'Stored settings',
      source: 'Source',
      storageFile: 'Storage file',
      activeEndpoint: 'Enabled endpoints',
    },
    sections: {
      endpoint: {
        eyebrow: 'Selected Endpoint',
        heading: 'Endpoint-Specific Settings',
        description: 'These settings apply only to the selected endpoint.',
      },
      common: {
        buttonLabel: 'Common Settings',
        eyebrow: 'Common Settings',
        heading: 'Common Settings',
        description: 'These settings apply to every endpoint.',
      },
    },
    toolbar: {
      addEndpoint: 'Add',
      duplicate: 'Duplicate',
      setActive: 'Enable',
      disableActive: 'Disable',
      selectedIsActive: 'Selected Is Enabled',
      removeSelected: 'Delete',
    },
    endpoint: {
      heading: 'Endpoint',
      name: 'Name',
      namePlaceholder: 'Primary Endpoint',
      type: 'Type',
      openAiCompatible: 'OpenAI-compatible',
      lmStudio: 'LM Studio',
      lmStudioNative: 'LM Studio Native',
      typeHint: 'Choose how this endpoint discovers models and sends chat requests.',
      typeDescriptions: {
        openAiCompatible: 'Recommended for most providers. Uses OpenAI-compatible model discovery and chat requests.',
        lmStudio: 'Recommended for LM Studio. Uses LM Studio model discovery for richer metadata, then sends chat through the OpenAI-compatible API so Copilot tools can be forwarded.',
        lmStudioNative: 'Advanced compatibility mode. Uses LM Studio native APIs for both model discovery and chat. VS Code custom tool definitions are not sent; choose this only when you need LM Studio native chat behavior.',
      },
      baseUrl: 'Base URL',
      baseUrlPlaceholder: 'http://127.0.0.1:1234',
      localhostRewrite: 'Container localhost rewrite',
      localhostRewriteHint: 'Auto rewrites localhost and 127.0.0.1 to host.docker.internal when running in a Docker container extension host. Turn Off if the endpoint actually runs inside the container.',
      defaultModel: 'Default model',
      defaultModelPlaceholder: 'Optional model id',
      apiKey: 'API key',
      apiKeySource: 'API key source',
      apiKeySourceSecretStorage: 'VS Code SecretStorage',
      apiKeySourceSecretStorageHint: 'Recommended. The key is stored separately per extension host and is not synced into containers.',
      apiKeySourceEnvironment: 'Environment variable',
      apiKeySourceEnvironmentHint: 'The key is read from the named environment variable in the current extension host. Good for Dev Containers and automation.',
      apiKeyEnvironmentVariable: 'Environment variable',
      apiKeyEnvironmentVariablePlaceholder: 'OPENROUTER_API_KEY',
    },
    connection: {
      heading: 'Connection',
      test: 'Test connection',
      testing: 'Testing...',
      statusIncomplete: 'Incomplete',
      statusNotChecked: 'Not tested',
      statusChecking: 'Checking',
      statusSuccess: 'Connected',
      statusChecked: 'Checked',
      statusError: 'Failed',
      statusRetest: 'Recheck',
      noBaseUrlHint: 'Enter a Base URL before running a connection test.',
      idleHint: 'Use Test connection to check whether this endpoint can return its model list.',
      testingHint: 'Trying to load the model list from this endpoint.',
      automaticSource: 'Last automatic check',
      manualSource: 'Last connection test',
      successWithModels: '{source}: fetched {count} chat model(s).',
      successWithoutModels: '{source}: connected, but no chat models were found.',
      previousSuccessWithModels: '{source}: previously fetched {count} chat model(s). Current connection state is unknown.',
      previousSuccessWithoutModels: '{source}: previously connected, but no chat models were found. Current connection state is unknown.',
      errorHint: '{source}: could not fetch the model list. Check the Base URL and API key.',
      previousErrorHint: '{source}: previous model-list fetch failed. Current connection state is unknown.',
    },
    capabilities: {
      heading: 'Tools',
      toolForwarding: 'Send tools to endpoint',
      toolForwardingHint: 'Use Off if the endpoint has trouble with tool calls, or if you want a reasoning-first no-tools mode without duplicate model entries. Off also stops advertising tool support to Copilot.',
      advertisedToolLimit: 'Tool limit',
      advertisedToolLimitPlaceholder: 'Optional',
      advertisedToolLimitHint: 'Optional. Limits how many tools this model reports and receives.',
      auto: 'Auto',
      on: 'On',
      off: 'Off',
    },
    requestOverrides: {
      heading: 'Request Options',
      reasoningEffort: 'Reasoning effort',
      reasoningEffortPlaceholder: 'high',
      reasoningEffortHint: 'Optional. Sent to endpoints that understand reasoning_effort.',
      lmStudioReasoning: 'LM Studio reasoning',
      lmStudioReasoningHint: 'Optional. Controls LM Studio Native reasoning mode.',
      enableThinking: 'Enable thinking',
      preserveThinking: 'Preserve thinking',
      preserveThinkingHint: 'Keeps hidden reasoning available for later turns when the endpoint supports it.',
      preservedThinkingMaxChars: 'Preserved thinking limit',
      preservedThinkingMaxCharsPlaceholder: '64000',
      preservedThinkingMaxCharsHint: 'Caps hidden thinking stored or replayed as reasoning_content, keeping the tail when truncated. Blank uses 64000 characters. Use 0 to keep response IDs but drop reasoning text. Use -1 to remove the cap, which is not recommended.',
      syntheticReasoningReplayMaxChars: 'Synthetic replay limit',
      syntheticReasoningReplayMaxCharsPlaceholder: '12000',
      syntheticReasoningReplayMaxCharsHint: 'Caps hidden thinking injected into synthetic system replay prompts, keeping both the beginning and end when truncated. Blank uses 12000 characters. Use 0 to disable synthetic replay. Use -1 to remove the cap, which is not recommended.',
      contextLength: 'Context length',
      contextLengthPlaceholder: '262144',
      maxTokens: 'Max tokens',
      maxTokensPlaceholder: '8192',
      temperature: 'Temperature',
      temperaturePlaceholder: '0',
      topP: 'Top P',
      topPPlaceholder: '1',
      topK: 'Top K',
      topKPlaceholder: '40',
      minP: 'Min P',
      minPPlaceholder: '0',
      presencePenalty: 'Presence penalty',
      presencePenaltyPlaceholder: '0',
      repeatPenalty: 'Repeat penalty',
      repeatPenaltyPlaceholder: '1',
      customJson: 'Custom JSON',
      customJsonHint: 'Advanced. Extra JSON to add to each request for this endpoint.',
      customJsonWarning: 'Keys that are not supported by the selected endpoint type are ignored.',
      auto: 'Auto',
      off: 'Off',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      on: 'On',
    },
    modelOverrides: {
      heading: 'Model Overrides',
      defaultToolCalling: 'Default tool support',
      defaultImageInput: 'Default image support',
      defaultMaxInputTokens: 'Default token limit',
      defaultMaxInputTokensPlaceholder: '262144',
      defaultHint: 'Applies to all models through the * default entry. Leave Auto or blank to keep upstream metadata. Token limit maps to maxInputTokens.',
      customJson: 'Custom JSON',
      customJsonHint: 'Advanced. Edit raw per-model overrides here. The simple defaults above update the matching fields in the * entry.',
      hint: 'Advanced. Override model names, token limits, image support, or tool support by model id. Use * as a default for all models.',
    },
    probe: {
      heading: 'Diagnostics',
      showModel: 'Probe model',
      showModelLabel: 'Show the diagnostic Probe model in the model picker',
      showModelHint: 'For troubleshooting only. Most users do not need this. Turn it on only when you want to check whether hidden chat data carries to the next turn.',
      debugLogs: 'Debug logs',
      debugLogsLabel: 'Write detailed request summaries to the output log',
      hiddenState: 'Hidden state',
      hiddenStateLabel: 'Attach hidden state to chat responses',
      mimeType: 'MIME type',
    },
    conversationState: {
      heading: 'Conversation Memory',
      diskPersistence: 'Keep after reload',
      diskPersistenceLabel: 'Keep conversation memory after reload or restart',
      diskPersistenceWarning: 'When enabled, hidden reasoning data and endpoint response ids are saved until they expire.',
      ttlMinutes: 'Expire after minutes',
      ttlMinutesPlaceholder: '720',
      maxEntries: 'Max entries',
      maxEntriesPlaceholder: '200',
    },
    display: {
      heading: 'Manager UI',
      language: 'Display language',
      hint: 'The panel reloads after this value changes.',
      auto: 'Auto (follow VS Code)',
      english: 'English',
      japanese: 'Japanese',
    },
    modelPicker: {
      heading: 'Model Picker',
      showModelsByDefault: 'Default visibility',
      showModelsByDefaultLabel: 'Show backend models in the model picker by default',
      showModelsByDefaultHint: 'When off, backend models start hidden until you enable them in the picker. Setup entries stay visible while the endpoint is unavailable so the manager stays reachable.',
    },
    actions: {
      heading: 'Actions',
      save: 'Save Settings File',
      openRawSettings: 'Open Settings File',
      importSyncedSettings: 'Import Synced Settings',
      importSyncedSettingsConfirmation: 'Import synced endpoint settings into this extension host?',
      importSyncedSettingsConfirmationDetail: 'This overwrites local non-secret endpoint settings. API keys are not synced; use SecretStorage or environment variables in this extension host.',
      exportEncryptedApiKeys: 'Export Encrypted API Keys',
      importEncryptedApiKeys: 'Import Encrypted API Keys',
      exportApiKeysPassphrasePrompt: 'Enter a passphrase to encrypt API keys for synced storage.',
      exportApiKeysPassphraseConfirmationPrompt: 'Re-enter the passphrase to confirm.',
      importApiKeysPassphrasePrompt: 'Enter the passphrase for synced encrypted API keys.',
      passphraseMismatch: 'Passphrases did not match. API keys were not exported.',
      showLogs: 'Show Logs',
      copyProbePrompt: 'Copy Probe test prompt',
    },
    dynamic: {
      endpointSingular: 'endpoint',
      endpointPlural: 'endpoints',
      none: 'None',
      apiKeyStored: 'API key stored',
      noApiKey: 'No API key',
      setApiKey: 'Set',
      clearApiKey: 'Clear',
      activeBadge: 'Enabled',
      registeredBadge: 'Disabled',
      errorBadge: 'Error',
      noBaseUrlConfigured: 'No base URL configured',
      sourceLabels: {
        storage: 'Settings file',
        defaults: 'Defaults',
        'legacy-configuration': 'Legacy configuration',
      },
      endpointDefaultNamePrefix: 'Endpoint',
      endpointFallbackName: 'Endpoint',
      endpointCopySuffix: 'Copy',
      endpointCopyFallbackName: 'Endpoint Copy',
      oneEndpointRequired: 'At least one endpoint must remain registered.',
      autoSaveSaving: 'Saving...',
      autoSaveSaved: 'Saved',
      autoSaveError: 'Save failed',
      removeEndpointAction: 'Delete Endpoint',
      removeEndpointConfirmation: 'Delete "{name}"?',
      removeEndpointConfirmationDetail: '',
      removeActiveEndpointConfirmation: '"{name}" is currently enabled. Delete it?',
      removeActiveEndpointConfirmationDetail: 'If this is the last enabled endpoint, models from this provider will disappear until another endpoint is enabled.',
      jsonLabels: {
        customRequest: 'Custom request JSON',
        modelOverrides: 'Model overrides JSON',
      },
      errors: {
        mustBeJsonObject: ' must be a JSON object.',
        mustBeValidJson: ' must be valid JSON. ',
        duplicateEndpointName: 'Endpoint names must be unique. "{name}" is already in use.',
      },
    },
  },
  ja: {
    htmlLang: 'ja',
    pageTitle: 'GHCC Custom Provider',
    sidebar: {
      eyebrow: '設定',
      description: 'チャット用の接続先を追加し、Copilot Chat に同時表示する接続先を選びます。',
      storedSettings: '保存済み設定',
      source: '読み込み元',
      storageFile: '保存ファイル',
      activeEndpoint: '有効な接続先',
    },
    sections: {
      endpoint: {
        eyebrow: '選択中の接続先',
        heading: '接続先ごとの設定',
        description: 'ここにある設定は、選択中の接続先にだけ適用されます。',
      },
      common: {
        buttonLabel: '共通設定',
        eyebrow: '共通設定',
        heading: '共通設定',
        description: 'ここにある設定は、すべての接続先に共通で適用されます。',
      },
    },
    toolbar: {
      addEndpoint: '追加',
      duplicate: '複製',
      setActive: '有効化',
      disableActive: '無効化',
      selectedIsActive: '選択中の接続先は有効です',
      removeSelected: '削除',
    },
    endpoint: {
      heading: '接続先',
      name: '名前',
      namePlaceholder: 'Primary Endpoint',
      type: '種別',
      openAiCompatible: 'OpenAI-compatible',
      lmStudio: 'LM Studio',
      lmStudioNative: 'LM Studio Native',
      typeHint: 'モデル取得とチャット送信に使う方式を選びます。',
      typeDescriptions: {
        openAiCompatible: '通常はこちらを選びます。OpenAI-compatible API でモデル一覧を取得し、チャットも送信します。',
        lmStudio: 'LM Studio ではこちらを推奨します。モデル一覧は LM Studio API から詳細情報を取得し、チャットは OpenAI-compatible API へ送るため、Copilot のツール定義を接続先へ転送できます。',
        lmStudioNative: '高度な互換モードです。モデル取得とチャットの両方に LM Studio Native API を使います。VS Code のカスタムツール定義は送信されないため、LM Studio のネイティブチャット挙動が必要な場合だけ選びます。',
      },
      baseUrl: 'Base URL',
      baseUrlPlaceholder: 'http://127.0.0.1:1234',
      localhostRewrite: 'コンテナ向け localhost 変換',
      localhostRewriteHint: 'Auto では Docker コンテナ内の拡張ホストで動作中、localhost と 127.0.0.1 を host.docker.internal に読み替えて接続します。接続先がコンテナ内で動いている場合は Off にしてください。',
      defaultModel: '既定モデル',
      defaultModelPlaceholder: '任意のモデル ID',
      apiKey: 'API key',
      apiKeySource: 'API key の取得元',
      apiKeySourceSecretStorage: 'VS Code SecretStorage',
      apiKeySourceSecretStorageHint: '推奨。API key は拡張ホストごとに分離保存され、コンテナへは同期されません。',
      apiKeySourceEnvironment: '環境変数',
      apiKeySourceEnvironmentHint: '現在の拡張ホスト上の環境変数名から API key を読みます。Dev Container や自動化に向いています。',
      apiKeyEnvironmentVariable: '環境変数名',
      apiKeyEnvironmentVariablePlaceholder: 'OPENROUTER_API_KEY',
    },
    connection: {
      heading: '接続テスト',
      test: '接続テスト',
      testing: '確認中...',
      statusIncomplete: '未入力',
      statusNotChecked: '未テスト',
      statusChecking: '確認中',
      statusSuccess: '接続OK',
      statusChecked: '確認済み',
      statusError: '失敗',
      statusRetest: '要再確認',
      noBaseUrlHint: 'Base URL を入力してから接続テストを実行します。',
      idleHint: '接続テスト を実行すると、この接続先からモデル一覧を取得できるか確認します。',
      testingHint: 'この接続先からモデル一覧を取得できるか確認しています。',
      automaticSource: '前回の自動確認',
      manualSource: '前回の接続テスト',
      successWithModels: '{source}: チャットに使えるモデルを {count} 件取得しました。',
      successWithoutModels: '{source}: 接続はできましたが、チャットに使えるモデルは見つかりませんでした。',
      previousSuccessWithModels: '{source}: 前回はチャットに使えるモデルを {count} 件取得しました。現在の接続状態は未確認です。',
      previousSuccessWithoutModels: '{source}: 前回は接続できましたが、チャットに使えるモデルは見つかりませんでした。現在の接続状態は未確認です。',
      errorHint: '{source}: モデル一覧を取得できませんでした。Base URL と API key を確認してください。',
      previousErrorHint: '{source}: 前回のモデル一覧取得は失敗しました。現在の接続状態は未確認です。',
    },
    capabilities: {
      heading: 'Tools',
      toolForwarding: 'ツールを接続先へ送る',
      toolForwardingHint: '接続先がツール呼び出しで失敗する場合や、モデル一覧を増やさずに推論重視の no-tools モードで使いたい場合は Off にします。Off では Copilot へのツール対応表示も止めます。',
      advertisedToolLimit: 'ツール上限',
      advertisedToolLimitPlaceholder: '任意',
      advertisedToolLimitHint: '任意。利用できると伝えるツール数と、実際に送るツール数を制限します。',
      auto: 'Auto',
      on: 'On',
      off: 'Off',
    },
    requestOverrides: {
      heading: 'Request Options',
      reasoningEffort: 'Reasoning effort',
      reasoningEffortPlaceholder: 'high',
      reasoningEffortHint: '任意。reasoning_effort に対応している接続先へ送ります。',
      lmStudioReasoning: 'LM Studio reasoning',
      lmStudioReasoningHint: '任意。LM Studio Native の推論モードを指定します。',
      enableThinking: 'Enable thinking',
      preserveThinking: 'Preserve thinking',
      preserveThinkingHint: '接続先が対応している場合、次の会話で非表示の推論情報を引き継げるようにします。',
      preservedThinkingMaxChars: 'Preserved thinking limit',
      preservedThinkingMaxCharsPlaceholder: '64000',
      preservedThinkingMaxCharsHint: 'reasoning_content として保存または再送する hidden thinking の上限です。超過時は末尾を残します。未入力時は 64000 文字までです。0 なら response ID は残しつつ推論本文を破棄します。-1 なら制限しませんが、非推奨です。',
      syntheticReasoningReplayMaxChars: 'Synthetic replay limit',
      syntheticReasoningReplayMaxCharsPlaceholder: '12000',
      syntheticReasoningReplayMaxCharsHint: '合成 system replay prompt に入れる hidden thinking の上限です。超過時は先頭と末尾を残します。未入力時は 12000 文字までです。0 なら合成 replay を無効化します。-1 なら制限しませんが、非推奨です。',
      contextLength: 'Context length',
      contextLengthPlaceholder: '262144',
      maxTokens: 'Max tokens',
      maxTokensPlaceholder: '8192',
      temperature: 'Temperature',
      temperaturePlaceholder: '0',
      topP: 'Top P',
      topPPlaceholder: '1',
      topK: 'Top K',
      topKPlaceholder: '40',
      minP: 'Min P',
      minPPlaceholder: '0',
      presencePenalty: 'Presence penalty',
      presencePenaltyPlaceholder: '0',
      repeatPenalty: 'Repeat penalty',
      repeatPenaltyPlaceholder: '1',
      customJson: 'Custom JSON',
      customJsonHint: '詳細設定。この接続先へ送るリクエストに追加する JSON です。',
      customJsonWarning: '選択中の接続種別で使えないキーは無視されます。',
      auto: 'Auto',
      off: 'Off',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      on: 'On',
    },
    modelOverrides: {
      heading: 'Model Overrides',
      defaultToolCalling: '既定のツール対応',
      defaultImageInput: '既定の画像対応',
      defaultMaxInputTokens: '既定のトークン上限',
      defaultMaxInputTokensPlaceholder: '262144',
      defaultHint: '全モデルに * の既定値として適用します。Auto または空欄なら接続先のメタデータをそのまま使います。トークン上限は maxInputTokens に反映します。',
      customJson: 'Custom JSON',
      customJsonHint: '詳細設定。モデルごとの生JSONをここで編集できます。上の簡易欄は保存時に * エントリの対応項目へ反映されます。',
      hint: '詳細設定。モデル ID ごとに表示名、トークン上限、画像対応、ツール対応を上書きできます。* を全モデルの既定値として使えます。',
    },
    probe: {
      heading: 'Diagnostics',
      showModel: 'Probe モデル',
      showModelLabel: 'モデル一覧に診断用の Probe モデルを表示',
      showModelHint: '不具合の切り分け用です。通常の利用では不要です。チャットの見えない内部データが次のやり取りにも渡っているか確認したいときだけ有効にします。',
      debugLogs: 'Debug logs',
      debugLogsLabel: '詳しいリクエスト概要を出力ログに記録',
      hiddenState: 'Hidden state',
      hiddenStateLabel: 'チャット応答に hidden state を付与',
      mimeType: 'MIME type',
    },
    conversationState: {
      heading: '会話メモリ',
      diskPersistence: '再読み込み後も保持',
      diskPersistenceLabel: '再読み込みや再起動のあとも会話メモリを保持',
      diskPersistenceWarning: '有効化すると、非表示の推論情報と接続先の response id が期限切れまで保存されます。',
      ttlMinutes: '保存期間（分）',
      ttlMinutesPlaceholder: '720',
      maxEntries: '最大件数',
      maxEntriesPlaceholder: '200',
    },
    display: {
      heading: 'Manager UI',
      language: '画面言語',
      hint: '変更後、この画面は自動で再読み込みされます。',
      auto: 'Auto (VS Code に追従)',
      english: 'English',
      japanese: '日本語',
    },
    modelPicker: {
      heading: 'モデルピッカー',
      showModelsByDefault: '既定の表示状態',
      showModelsByDefaultLabel: 'バックエンドモデルをモデルピッカーへ既定で表示する',
      showModelsByDefaultHint: 'Off のとき、バックエンドモデルは最初は非表示で始まります。接続先が未設定・未接続の間も setup 項目だけは表示を維持し、管理画面を開き直しやすくします。',
    },
    actions: {
      heading: '操作',
      save: '設定ファイルを保存',
      openRawSettings: '設定ファイルを開く',
      importSyncedSettings: '同期設定を取り込む',
      importSyncedSettingsConfirmation: '同期済みの接続先設定をこの拡張ホストへ取り込みますか？',
      importSyncedSettingsConfirmationDetail: 'ローカルの非シークレット接続先設定を上書きします。API key は同期されないため、この拡張ホストの SecretStorage または環境変数を使ってください。',
      exportEncryptedApiKeys: 'API key を暗号化して同期',
      importEncryptedApiKeys: '暗号化 API key を取り込む',
      exportApiKeysPassphrasePrompt: 'API key を同期領域へ暗号化保存するためのパスフレーズを入力してください。',
      exportApiKeysPassphraseConfirmationPrompt: '確認のため、同じパスフレーズをもう一度入力してください。',
      importApiKeysPassphrasePrompt: '同期済みの暗号化 API key を復号するパスフレーズを入力してください。',
      passphraseMismatch: 'パスフレーズが一致しません。API key は同期されませんでした。',
      showLogs: 'ログを表示',
      copyProbePrompt: 'Probe テスト文をコピー',
    },
    dynamic: {
      endpointSingular: 'endpoint',
      endpointPlural: 'エンドポイント',
      none: 'なし',
      apiKeyStored: 'API key 保存済み',
      noApiKey: 'API key 未設定',
      setApiKey: '設定',
      clearApiKey: '削除',
      activeBadge: '有効',
      registeredBadge: '無効',
      errorBadge: 'エラー',
      noBaseUrlConfigured: 'Base URL 未設定',
      sourceLabels: {
        storage: '設定ファイル',
        defaults: '既定値',
        'legacy-configuration': '旧設定から移行',
      },
      endpointDefaultNamePrefix: 'エンドポイント',
      endpointFallbackName: 'エンドポイント',
      endpointCopySuffix: 'コピー',
      endpointCopyFallbackName: 'エンドポイント コピー',
      oneEndpointRequired: '最低 1 つの endpoint は残す必要があります。',
      autoSaveSaving: '保存中...',
      autoSaveSaved: '保存済み',
      autoSaveError: '保存に失敗しました',
      removeEndpointAction: '接続先を削除',
      removeEndpointConfirmation: '「{name}」を削除しますか？',
      removeEndpointConfirmationDetail: '',
      removeActiveEndpointConfirmation: '「{name}」は現在有効です。削除しますか？',
      removeActiveEndpointConfirmationDetail: 'これが最後の有効な接続先だった場合、別の接続先を有効化するまでこのプロバイダーのモデルは表示されません。',
      jsonLabels: {
        customRequest: 'Custom request JSON',
        modelOverrides: 'Model overrides JSON',
      },
      errors: {
        mustBeJsonObject: ' は JSON object である必要があります。',
        mustBeValidJson: ' は有効な JSON である必要があります。',
        duplicateEndpointName: '接続先名は一意である必要があります。"{name}" はすでに使われています。',
      },
    },
  },
} as const;

export type ManagerText = (typeof MANAGER_TEXT)[ManagerLocale];

export function resolveManagerLocale(mode: ManagerLanguageMode, hostLanguage: string): ManagerLocale {
  if (mode === 'ja') {
    return 'ja';
  }

  if (mode === 'en') {
    return 'en';
  }

  return hostLanguage.trim().toLowerCase().startsWith('ja') ? 'ja' : 'en';
}

export function getManagerText(locale: ManagerLocale): ManagerText {
  return MANAGER_TEXT[locale];
}